In [4]:
import gym
import tensorflow as tf
from tensorflow import keras
import numpy as np

model = keras.models.load_model("ann_models/mnist_ann.h5")

model.save("ann_models/mnist_ann")



Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: ann_models/mnist_ann/assets


In [5]:
import os
import googleapiclient.discovery

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "lustrous-spirit-289115-d04c125a846b.json"

project_id = 'lustrous-spirit-289115'

model_id = 'mnist'

model_path = "projects/{}/models/{}".format(project_id, model_id)

ml_resource = googleapiclient.discovery.build("ml", "v1").projects()

In [29]:
def predict(X):
    
    input_data_json = {"signature_name": "serving_default",
                       "instances": X.tolist()}
    
    request = ml_resource.predict(name=model_path, body=input_data_json)
    
    response = request.execute()
    
    if "error" in response:
        
        raise RuntimeError(response['error'])
        
    return np.array([pred['dense_83'] for pred in response["predictions"]])



In [31]:
mnist_dataset = keras.datasets.mnist.load_data()


for i in range(100):
    
    Y_probas = predict(mnist_dataset[0][0][:32].reshape(32, 28, 28, 1))

    predictions = np.argmax(Y_probas, axis=-1)
    
    print(predictions)

[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8]
[5 0 4 1 9

In [2]:
print("Hello")

Hello


In [3]:
model = keras.models.load_model("ann_models/bach_ann.h5")

NameError: name 'keras' is not defined